---

- name: "run 'brew uninstall --force {{ item }}'"
  shell: "brew uninstall --force {{ item }}"
  ignore_errors: true

- name: "run 'rm -r /usr/local/etc/vsh-*'"
  shell: "rm -r /usr/local/etc/vsh-*"
  ignore_errors: true

- name: "run 'brew install --build-bottle --formula {{ formula_path }}/{{ item }}'"
  shell: "brew install --build-bottle --formula {{ formula_path }}/{{ item }} -vvv"

- name: "run 'brew bottle {{ formula_path }}/{{ item }} --json --force-core-tap --no-rebuild'"
  shell: "brew bottle {{ formula_path }}/{{ item }} --json --force-core-tap --no-rebuild"
