name: 'tests'

on:
  schedule:
    - cron: "30 3 * * 0"
  push:
    branches:
      - master
jobs:
  tests-on-macos-14-large:
    runs-on: macos-14-large
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/.github/scripts/brew-install-tests.sh
      shell: bash
  tests-on-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/.github/scripts/brew-install-tests-arm.sh
      shell: bash
